# Generated by Django 4.2 on 2023-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_uri',
            field=models.SlugField(blank=True, default='', verbose_name='ParentURL'),
        ),
    ]
