# Generated by Django 4.2 on 2023-05-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_menu_parent_alter_menu_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('uri',), 'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
    ]
